2025-07-08 23:19:19,949 - asyncio - DEBUG - Using proactor: IocpProactor
2025-07-08 23:19:19,955 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:19:19,958 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:19:19,972 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:19:19,973 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:19:19,989 - __main__ - INFO - Telegram Manager Bot started. Send /menu to interact.
2025-07-08 23:19:19,990 - telegram.ext.ExtBot - DEBUG - Entering: send_message
2025-07-08 23:19:20,002 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:19:20,017 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectError(gaierror(11001, 'getaddrinfo failed'))
2025-07-08 23:19:20,019 - __main__ - ERROR - Could not send startup message to TELEGRAM_CHAT_ID 7049055170: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-07-08 23:19:20,021 - telegram.ext.ExtBot - DEBUG - Entering: get_me
2025-07-08 23:19:20,025 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:19:20,027 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectError(gaierror(11001, 'getaddrinfo failed'))
2025-07-08 23:19:20,030 - telegram.ext.Application - DEBUG - This Application is already shut down. Returning.
2025-07-08 23:19:20,031 - __main__ - ERROR - Error in polling: httpx.ConnectError: [Errno 11001] getaddrinfo failed
